-- Generated by Brain_Shell (matugen) — NvChad base46 cache (wal-style)
-- Place/point your NvChad base46 override at this file.
local M = {}

M.base_30 = {
  white         = "{{colors.on_surface.default.hex}}",
  darker_black  = "{{colors.surface_dim.default.hex}}",
  black         = "{{colors.surface.default.hex}}",
  black2        = "{{colors.surface_container_low.default.hex}}",
  one_bg        = "{{colors.surface_container.default.hex}}",
  one_bg2       = "{{colors.surface_container_high.default.hex}}",
  one_bg3       = "{{colors.surface_container_highest.default.hex}}",
  grey          = "{{colors.outline.default.hex}}",
  grey_fg       = "{{colors.outline_variant.default.hex}}",
  light_grey    = "{{colors.on_surface_variant.default.hex}}",
  red           = "{{colors.red.default.hex}}",
  baby_pink     = "{{colors.magenta.default.hex}}",
  pink          = "{{colors.magenta.default.hex}}",
  line          = "{{colors.outline_variant.default.hex}}",
  green         = "{{colors.green.default.hex}}",
  vibrant_green = "{{colors.green.default.hex}}",
  blue          = "{{colors.blue.default.hex}}",
  nord_blue     = "{{colors.primary.default.hex}}",
  yellow        = "{{colors.yellow.default.hex}}",
  sun           = "{{colors.yellow.default.hex}}",
  purple        = "{{colors.tertiary.default.hex}}",
  dark_purple   = "{{colors.tertiary.default.hex}}",
  teal          = "{{colors.cyan.default.hex}}",
  orange        = "{{colors.tertiary.default.hex}}",
  cyan          = "{{colors.cyan.default.hex}}",
}

M.base_16 = {
  base00 = "{{colors.surface.default.hex}}",
  base01 = "{{colors.surface_container_low.default.hex}}",
  base02 = "{{colors.surface_container.default.hex}}",
  base03 = "{{colors.outline.default.hex}}",
  base04 = "{{colors.on_surface_variant.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.on_surface.default.hex}}",
  base07 = "{{colors.primary.default.hex}}",
  base08 = "{{colors.red.default.hex}}",
  base09 = "{{colors.tertiary.default.hex}}",
  base0A = "{{colors.yellow.default.hex}}",
  base0B = "{{colors.green.default.hex}}",
  base0C = "{{colors.cyan.default.hex}}",
  base0D = "{{colors.blue.default.hex}}",
  base0E = "{{colors.magenta.default.hex}}",
  base0F = "{{colors.tertiary.default.hex}}",
}

M.type = "dark"
return M
