#!/bin/bash

# Brain Shell — Main Installation Script

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

clear
echo "Brain Shell — Installation"
echo "github.com/Brainitech/Brain_Shell v0.1.0"
echo ""

log_info "Starting Brain Shell installation..."
echo ""

if [[ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]]; then
    log_warn "Not running in Hyprland. Installation will proceed, but you must"
    log_warn "restart Hyprland after completion for changes to take effect."
    echo ""
fi

if [[ ! "$OSTYPE" =~ ^linux ]]; then
    log_error "This installer only supports Linux systems."
    exit 1
fi

log_info "Detecting Linux distribution..."

DISTRO=""

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    DISTRO="$ID"
elif [[ -f /etc/lsb-release ]]; then
    . /etc/lsb-release
    DISTRO="$DISTRIB_ID"
fi

case "$DISTRO" in
    arch|manjaro|garuda|cachyos|endeavouros)
        log_success "Detected: Arch-based distro ($DISTRO)"
        DISTRO_TYPE="arch"
        ;;
    nixos)
        log_success "Detected: NixOS"
        DISTRO_TYPE="nix"
        ;;
    *)
        log_error "Unsupported distribution: $DISTRO"
        log_error "Currently supported: Arch Linux, Manjaro, Garuda, CachyOS, EndeavourOS, NixOS"
        exit 1
        ;;
esac

echo ""
echo -e "${YELLOW}Choose install mode:${NC}"
echo "  1) Step-by-step — asks before each step"
echo "  2) Quick — asks once, then auto-pilot"
echo ""
echo -ne "${BLUE}[Choice 1-2]:${NC} "
read -r mode_choice

case "$mode_choice" in
    2) MODE="quick" ;;
    *) MODE="stepbystep" ;;
esac

echo ""
CONFIG_DIR="$HOME/.config"
BACKUP_DIR=""

if [[ "$MODE" == "quick" ]]; then
    echo -ne "${YELLOW}?${NC} Proceed with full installation? [Y/n]: "
    read -r proceed
    if [[ "$proceed" =~ ^[Nn] ]]; then
        log_warn "Installation cancelled."
        exit 0
    fi
    log_info "Quick mode. Creating backup automatically..."
    BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="$HOME/.config.backup-${BACKUP_TIMESTAMP}"
    if [[ -d "$CONFIG_DIR" ]]; then
        cp -r "$CONFIG_DIR" "$BACKUP_DIR"
        log_success "Backup created: ${BACKUP_DIR##*/}"
    else
        log_warn "~/.config does not exist. Skipping backup."
        BACKUP_DIR=""
    fi
else
    echo -e "${YELLOW}Backup ~/.config?${NC}"
    echo "  1) Yes, create backup"
    echo "  2) No, skip"
    echo ""
    echo -ne "${BLUE}[Choice 1-2]:${NC} "
    read -r backup_choice

    case "$backup_choice" in
        2)
            log_warn "Skipping backup."
            BACKUP_DIR="skipped"
            ;;
        *)
            log_info "Creating backup..."
            BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
            BACKUP_DIR="$HOME/.config.backup-${BACKUP_TIMESTAMP}"
            if [[ -d "$CONFIG_DIR" ]]; then
                cp -r "$CONFIG_DIR" "$BACKUP_DIR"
                log_success "Backup created: ${BACKUP_DIR##*/}"
                log_info "Restore with: cp -r \"$BACKUP_DIR\" \"$CONFIG_DIR\""
            else
                log_warn "~/.config does not exist. Skipping backup."
                BACKUP_DIR=""
            fi
            ;;
    esac
fi

echo ""

log_info "Validating Hyprland configuration..."

HYPRLAND_CONF_PATH="$CONFIG_DIR/hypr/hyprland.conf"
HYPRLAND_LUA_PATH="$CONFIG_DIR/hypr/hyprland.lua"

if [[ -f "$HYPRLAND_CONF_PATH" ]]; then
    HYPRLAND_CONF="$HYPRLAND_CONF_PATH"
    log_success "Hyprland config found (.conf)."
elif [[ -f "$HYPRLAND_LUA_PATH" ]]; then
    HYPRLAND_CONF="$HYPRLAND_LUA_PATH"
    log_success "Hyprland config found (.lua)."
else
    log_warn "No Hyprland config found. Creating default..."
    mkdir -p "$CONFIG_DIR/hypr"
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    if [[ -f "$SCRIPT_DIR/dots-extra/hyprland.lua" ]]; then
        cp "$SCRIPT_DIR/dots-extra/hyprland.lua" "$HYPRLAND_LUA_PATH"
        log_success "Copied default hyprland.lua from dots-extra."
    else
        cat > "$HYPRLAND_LUA_PATH" << 'LUA'
-- Generated by Brain Shell installer
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.config({
    general = { gaps_in = 5, gaps_out = 20, border_size = 2,
        col = { active_border = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 }, inactive_border = "rgba(595959aa)" },
        layout = "dwindle" },
    decoration = { rounding = 10, active_opacity = 1.0, inactive_opacity = 1.0,
        shadow = { enabled = true, range = 4, render_power = 3, color = 0xee1a1a1a },
        blur = { enabled = true, size = 3, passes = 1 } },
    animations = { enabled = true },
    input = { kb_layout = "us", follow_mouse = 1 },
    misc = { force_default_wallpaper = -1, disable_hyprland_logo = false },
})
local mainMod = "SUPER"
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("hyprlauncher"))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
for i = 1, 10 do local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
LUA
        log_success "Created minimal hyprland.lua."
    fi
    HYPRLAND_CONF="$HYPRLAND_LUA_PATH"
fi
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

DISTRO_INSTALLER="$SCRIPT_DIR/dots-extra/install-${DISTRO_TYPE}.sh"

if [[ ! -f "$DISTRO_INSTALLER" ]]; then
    log_error "Distro installer not found: $DISTRO_INSTALLER"
    exit 1
fi

log_info "Executing distro-specific installer..."
echo ""

bash "$DISTRO_INSTALLER" "$HYPRLAND_CONF" "$BACKUP_DIR" "$MODE"

echo ""
log_success "Brain Shell installation complete!"
echo ""
log_warn "You must restart Hyprland for changes to take effect."
log_info "Restart options:"
log_info "  • Exit and log back in (preferred)"
log_info "  • Press Ctrl+Alt+Q in Hyprland (if configured)"
log_info "  • Run: hyprctl dispatch exit"
echo ""
log_info "After restart, Brain Shell will launch automatically via exec-once."
echo ""
log_info "Configuration located at: ~/.config/Brain_Shell"
log_info "Repository cloned to: ~/.local/src/Brain_Shell"
echo ""

exit 0
