pragma Singleton
import QtQuick
import Quickshell.Io
import Quickshell
import "../"

/*!
    HyprlandSyncService — regenerates hyprland.lua when keybinds change.

    Reads Brain_Shell's keybinds.json and writes a complete hyprland.lua
    to ~/.local/share/Brain_Shell/ with autostart + hl.bind() entries.
    Triggered automatically when KeybindService saves changes.
*/
QtObject {
    id: root

    readonly property string _dataDir: Quickshell.env("HOME") + "/.local/share/Brain_Shell"
    readonly property string _luaPath: _dataDir + "/hyprland.lua"
    readonly property string _confPath: _dataDir + "/hyprland.conf"

    // ── Keybind definitions (same targets as IpcManager) ─────────────────────
    readonly property var _bindMap: ([
        { target: "dashboard-home",     combo: "SUPER + D",              cli: "dashboard-home" },
        { target: "dashboard-stats",    combo: "CTRL + SHIFT + ESCAPE",  cli: "dashboard-stats" },
        { target: "dashboard-kanban",   combo: "SUPER + Z",              cli: "dashboard-kanban" },
        { target: "dashboard-launcher", combo: "SUPER + Q",              cli: "dashboard-launcher" },
        { target: "dashboard-config",   combo: "SUPER + C",              cli: "dashboard-config" },
        { target: "PowerMenu-toggle",   combo: "SUPER + ESCAPE",         cli: "arch-menu" },
        { target: "notifications-toggle", combo: "SUPER + N",            cli: "notifications" },
        { target: "wallpaper-toggle",   combo: "SUPER + W",              cli: "wallpaper" },
        { target: "clipboard-toggle",   combo: "SUPER + V",              cli: "clipboard" },
        { target: "wifi-toggle",        combo: "SUPER + ALT + W",        cli: "wifi-toggle" },
        { target: "bt-toggle",          combo: "SUPER + ALT + B",        cli: "bt-toggle" },
        { target: "vpn-toggle",         combo: "SUPER + ALT + G",        cli: "vpn-toggle" },
        { target: "hotspot-toggle",     combo: "SUPER + ALT + H",        cli: "hotspot-toggle" },
        { target: "audioOut-toggle",    combo: "SUPER + A",              cli: "audio" },
        { target: "audioIn-toggle",     combo: "SUPER + ALT + I",        cli: "audio" },
        { target: "audioMix-toggle",    combo: "SUPER + M",              cli: "audio" },
        { target: "focus-toggle",       combo: "SUPER + F",              cli: "focus" },
        { target: "screenrec-on",       combo: "SUPER + R",              cli: "screen-record" },
    ])

    // ── Load user overrides from keybinds.json ────────────────────────────────
    // Returns a map: target → combo string, or target → "" (disabled).
    // Targets NOT in overrides use their default combo.
    function _loadOverrides() {
        var overrides = {};
        try {
            var raw = KeybindService.keybinds;
            if (raw && typeof raw === "object") {
                for (var target in raw) {
                    if (!raw[target]) continue;
                    var mods = raw[target].mods || "";
                    var key  = raw[target].key  || "";
                    if (mods !== "" && key !== "") {
                        // User set a custom combo
                        overrides[target] = mods + " + " + key;
                    } else {
                        // User explicitly disabled this bind — mark as empty
                        overrides[target] = "";
                    }
                }
            }
        } catch (e) {
            console.warn("HyprlandSyncService: failed to load keybinds:", e);
        }
        return overrides;
    }

    // ── Generate hyprland.lua content ─────────────────────────────────────────
    function _generateLua() {
        var overrides = _loadOverrides();
        var lines = [];

        lines.push("-- ═══════════════════════════════════════════════════════════════════════════");
        lines.push("--  Brain_Shell — generated by HyprlandSyncService");
        lines.push("--  Regenerated on keybind changes. Do not edit manually.");
        lines.push("-- ═══════════════════════════════════════════════════════════════════════════");
        lines.push("");
        lines.push("-- ── Autostart ───────────────────────────────────────────────────────────────");
        lines.push('hl.on("hyprland.start", function ()');
        lines.push('    hl.exec_cmd("brain-shell")');
        lines.push("end)");
        lines.push("");
        lines.push("-- ── Keybinds ────────────────────────────────────────────────────────────────");

        for (var i = 0; i < _bindMap.length; i++) {
            var b = _bindMap[i];
            // Check if user explicitly disabled this bind
            if (overrides.hasOwnProperty(b.target) && overrides[b.target] === "") {
                continue;  // user disabled this bind — skip
            }
            var combo = overrides[b.target] || b.combo;
            lines.push('hl.bind("' + combo + '", hl.dsp.exec_cmd("brain-shell run ' + b.cli + '"))');
        }

        lines.push("");
        return lines.join("\n") + "\n";
    }

    // ── Generate hyprland.conf content ────────────────────────────────────────
    function _generateConf() {
        var overrides = _loadOverrides();
        var lines = [];

        lines.push("# Brain_Shell — generated by HyprlandSyncService");
        lines.push("exec-once = brain-shell");
        lines.push("");

        for (var i = 0; i < _bindMap.length; i++) {
            var b = _bindMap[i];
            // Skip disabled binds
            if (overrides.hasOwnProperty(b.target) && overrides[b.target] === "") {
                continue;
            }
            var combo = overrides[b.target] || b.combo;
            // Convert "SUPER + A" → "$mainMod, A" for .conf format
            var confCombo = combo.replace(/SUPER/g, "$mainMod").replace(/ \+ /g, ", ");
            lines.push("bind = " + confCombo + ", exec, brain-shell run " + b.cli);
        }

        lines.push("");
        return lines.join("\n") + "\n";
    }

    // ── Write to disk ─────────────────────────────────────────────────────────
    property Process _writeProc: Process {
        command: []
        running: false
    }

    function sync() {
        var lua = _generateLua();
        var conf = _generateConf();

        // Write both files atomically via bash, then reload Hyprland
        _writeProc.command = ["bash", "-c",
            "mkdir -p '" + _dataDir + "' && " +
            "printf '%s' '" + lua.replace(/'/g, "'\\''") + "' > '" + _luaPath + "' && " +
            "printf '%s' '" + conf.replace(/'/g, "'\\''") + "' > '" + _confPath + "' && " +
            "hyprctl reload 2>/dev/null || true"
        ];
        _writeProc.running = false;
        _writeProc.running = true;

        console.log("HyprlandSyncService: synced binds to", _luaPath);
    }

    // ── Auto-sync on keybind changes ──────────────────────────────────────────
    property Timer _debounce: Timer {
        interval: 1000
        repeat: false
        onTriggered: root.sync()
    }

    // Delay keybind watching until KeybindService is available
    property Timer _watchTimer: Timer {
        interval: 5000
        running: true
        onTriggered: _setupWatcher()
    }

    function _setupWatcher() {
        try {
            if (typeof KeybindService !== "undefined" && KeybindService) {
                _keybindWatcher.target = KeybindService;
            }
        } catch (e) {
            console.warn("HyprlandSyncService: KeybindService not available yet");
        }
    }

    property var _keybindWatcher: Connections {
        target: null
        function onKeybindsChanged() {
            root._debounce.restart();
        }
    }

    // ── Initial sync on startup ───────────────────────────────────────────────
    property Timer _initTimer: Timer {
        interval: 3000
        running: true
        onTriggered: root.sync()
    }

    // ── IPC handler for manual sync (brain-shell sync) ───────────────────────
    property var _ipcHandler: IpcHandler {
        target: "sync-binds"
        function toggle() {
            root.sync();
            console.log("HyprlandSyncService: manual sync triggered via IPC");
        }
    }
}
