pragma Singleton
import QtQuick
import Quickshell.Io
import Quickshell
import "../"

/*!
    HyprlandSyncService — regenerates hyprland.lua when keybinds change.

    Reads Brain_Shell's keybinds.json and writes a complete hyprland.lua
    to ~/.local/share/Brain_Shell/ with autostart + hl.bind() entries.
    Triggered automatically when KeybindService saves changes.
*/
QtObject {
    id: root

    readonly property string _dataDir: Quickshell.env("HOME") + "/.local/share/Brain_Shell"
    readonly property string _luaPath: _dataDir + "/hyprland.lua"
    readonly property string _confPath: _dataDir + "/hyprland.conf"

    // ── Keybind definitions (same targets as IpcManager) ─────────────────────
    readonly property var _bindMap: ([
        { target: "dashboard-home",     combo: "SUPER + D",              cli: "dashboard-home" },
        { target: "dashboard-stats",    combo: "CTRL + SHIFT + ESCAPE",  cli: "dashboard-stats" },
        { target: "dashboard-kanban",   combo: "SUPER + Z",              cli: "dashboard-kanban" },
        { target: "dashboard-launcher", combo: "SUPER + Q",              cli: "dashboard-launcher" },
        { target: "dashboard-config",   combo: "SUPER + C",              cli: "dashboard-config" },
        { target: "PowerMenu-toggle",   combo: "SUPER + ESCAPE",         cli: "arch-menu" },
        { target: "notification-toggle", combo: "SUPER + N",            cli: "notification-toggle" },
        { target: "wallpaper-toggle",   combo: "SUPER + W",              cli: "wallpaper" },
        { target: "clipboard-toggle",   combo: "SUPER + V",              cli: "clipboard" },
        { target: "wifi-toggle",        combo: "SUPER + ALT + W",        cli: "wifi-toggle" },
        { target: "bluetooth-toggle",  combo: "SUPER + ALT + B",        cli: "bluetooth-toggle" },
        { target: "vpn-toggle",         combo: "SUPER + ALT + G",        cli: "vpn-toggle" },
        { target: "hotspot-toggle",     combo: "SUPER + ALT + H",        cli: "hotspot-toggle" },
        { target: "audioOut-toggle",    combo: "SUPER + A",              cli: "audioOut-toggle" },
        { target: "audioIn-toggle",     combo: "SUPER + ALT + I",        cli: "audioIn-toggle" },
        { target: "audioMix-toggle",    combo: "SUPER + M",              cli: "audioMix-toggle" },
        { target: "focus-toggle",       combo: "SUPER + F",              cli: "focus" },
        { target: "screenrec-on",       combo: "SUPER + R",              cli: "screen-record" },
    ])

    // ── Load user overrides from keybinds.json ────────────────────────────────
    // Returns a map: target → combo string, or target → "" (disabled).
    // Targets NOT in overrides use their default combo.
    function _loadOverrides() {
        var overrides = {};
        try {
            var raw = KeybindService.keybinds;
            if (raw && typeof raw === "object") {
                for (var target in raw) {
                    if (!raw[target]) continue;
                    var mods = raw[target].mods || "";
                    var key  = raw[target].key  || "";
                    if (mods !== "" && key !== "") {
                        // User set a custom combo
                        overrides[target] = mods + " + " + key;
                    } else {
                        // User explicitly disabled this bind — mark as empty
                        overrides[target] = "";
                    }
                }
            }
        } catch (e) {
            console.warn("HyprlandSyncService: failed to load keybinds:", e);
        }
        return overrides;
    }

    // ── Generate hyprland.lua content ─────────────────────────────────────────
    function _generateLua() {
        var overrides = _loadOverrides();
        var lines = [];

        lines.push("-- ═══════════════════════════════════════════════════════════════════════════");
        lines.push("--  Brain_Shell — generated by HyprlandSyncService");
        lines.push("--  Regenerated on keybind changes. Do not edit manually.");
        lines.push("-- ═══════════════════════════════════════════════════════════════════════════");
        lines.push("");
        lines.push("-- ── Autostart ───────────────────────────────────────────────────────────────");
        lines.push('hl.on("hyprland.start", function ()');
        lines.push('    hl.exec_cmd("brain-shell")');
        lines.push("end)");
        lines.push("");
        lines.push("-- ── Window rules (quickshell integration) ──────────────────────────────────");
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, no_blur = true })');
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, border_size = 0 })');
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, no_anim = true })');
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, rounding = 0 })');
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, stay_focused = true })');
        lines.push('hl.window_rule({ match = { class = "^(quickshell)$" }, no_max_size = true })');
        lines.push("");
        lines.push("-- ── Layer rules (quickshell integration) ────────────────────────────────────");
        lines.push('hl.layer_rule({ match = { namespace = "^(quickshell)$" }, blur = true })');
        lines.push('hl.layer_rule({ match = { namespace = "^(quickshell)$" }, ignore_alpha = 0 })');
        lines.push('hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })');
        lines.push("");
        lines.push("-- ── Submap for keybind interception (ShellState / KeybindService) ───────────");
        lines.push('hl.define_submap("BrainShell_clean", function()');
        lines.push('    hl.bind("Escape", hl.dsp.submap("reset"))');
        lines.push("end)");
        lines.push("");
        lines.push("-- ── Keybinds ────────────────────────────────────────────────────────────────");

        for (var i = 0; i < _bindMap.length; i++) {
            var b = _bindMap[i];
            // Check if user explicitly disabled this bind
            if (overrides.hasOwnProperty(b.target) && overrides[b.target] === "") {
                continue;  // user disabled this bind — skip
            }
            var combo = overrides[b.target] || b.combo;
            lines.push('hl.bind("' + combo + '", hl.dsp.exec_cmd("brain-shell run ' + b.cli + '"))');
        }

        lines.push("");
        return lines.join("\n") + "\n";
    }

    // ── Generate hyprland.conf content ────────────────────────────────────────
    function _generateConf() {
        var overrides = _loadOverrides();
        var lines = [];

        lines.push("# Brain_Shell — generated by HyprlandSyncService");
        lines.push("# Regenerated on keybind changes. Do not edit manually.");
        lines.push("");
        lines.push("$mainMod = SUPER");
        lines.push("");
        lines.push("exec-once = brain-shell");
        lines.push("");

        // ── Window rules (quickshell integration) ────────────────────────────
        lines.push("windowrule = no_blur on, match:class ^(quickshell)$");
        lines.push("windowrule = border_size 0, match:class ^(quickshell)$");
        lines.push("windowrule = no_anim on, match:class ^(quickshell)$");
        lines.push("windowrule = rounding 0, match:class ^(quickshell)$");
        lines.push("windowrule = stay_focused on, match:class ^(quickshell)$");
        lines.push("windowrule = no_max_size on, match:class ^(quickshell)$");
        lines.push("");

        // ── Layer rules (quickshell integration) ─────────────────────────────
        lines.push("layerrule = blur on, match:namespace ^(quickshell)$");
        lines.push("layerrule = ignore_alpha 0, match:namespace ^(quickshell)$");
        lines.push("layerrule = no_anim on, match:namespace ^(quickshell)$");
        lines.push("");

        // ── Keybinds ─────────────────────────────────────────────────────────
        for (var i = 0; i < _bindMap.length; i++) {
            var b = _bindMap[i];
            // Skip disabled binds
            if (overrides.hasOwnProperty(b.target) && overrides[b.target] === "") {
                continue;
            }
            var combo = overrides[b.target] || b.combo;
            // Split combo into modifiers (space-separated) and key
            // "SUPER + D"            → mods="SUPER",     key="D"
            // "CTRL + SHIFT + ESCAPE" → mods="CTRL SHIFT", key="ESCAPE"
            var parts = combo.split(" + ");
            var key = parts.pop();
            var mods = parts.join(" ");
            // Convert SUPER → $mainMod (consistent with user config conventions)
            mods = mods.replace(/SUPER/g, "$mainMod");
            // Handle single-modifier SUPER-as-only-modifier case
            if (mods === "" && key === "") continue;

            var bindLine;
            if (mods) {
                bindLine = "bind = " + mods + ", " + key + ", exec, brain-shell run " + b.cli;
            } else {
                bindLine = "bind = , " + key + ", exec, brain-shell run " + b.cli;
            }
            lines.push(bindLine);
        }

        lines.push("");
        return lines.join("\n") + "\n";
    }

    // ── Write to disk ─────────────────────────────────────────────────────────
    property Process _writeProc: Process {
        command: []
        running: false
    }

    function sync() {
        var lua = _generateLua();
        var conf = _generateConf();

        // Escape backslashes and single quotes for safe printf '%s' usage
        var le = lua.replace(/\\/g, "\\\\").replace(/'/g, "'\\''");
        var ce = conf.replace(/\\/g, "\\\\").replace(/'/g, "'\\''");

        _writeProc.command = ["bash", "-c",
            "mkdir -p '" + _dataDir + "' && " +
            "printf '%s' '" + le + "' > '" + _luaPath + "' && " +
            "printf '%s' '" + ce + "' > '" + _confPath + "'"
        ];
        _writeProc.running = false;
        _writeProc.running = true;

        console.log("HyprlandSyncService: synced", _bindMap.length, "binds to", _luaPath);
    }

    property Process _reloadProc: Process {
        command: ["hyprctl", "reload"]
        running: false
    }

    // ── Auto-sync on keybind changes ──────────────────────────────────────────
    property Timer _debounce: Timer {
        interval: 150
        repeat: false
        onTriggered: {
            root.sync()
            // Reload Hyprland so the new bind file takes effect immediately
            root._reloadAfterSync.restart()
        }
    }

    property Timer _reloadAfterSync: Timer {
        interval: 200
        repeat: false
        onTriggered: {
            root._reloadProc.running = false
            root._reloadProc.running = true
        }
    }

    // KeybindService is a singleton — available when this object instantiates.
    property var _keybindWatcher: Connections {
        target: KeybindService
        function onKeybindsChanged() {
            root._debounce.restart()
        }
    }

    // ── Initial sync on startup ───────────────────────────────────────────────
    property Timer _initTimer: Timer {
        interval: 500
        running: true
        onTriggered: root.sync()
    }

    // ── IPC handler for manual sync (brain-shell sync) ───────────────────────
    property var _ipcHandler: IpcHandler {
        target: "sync-binds"
        function toggle() {
            root.sync();
            console.log("HyprlandSyncService: manual sync triggered via IPC");
        }
    }
}
