# Home Manager module — user-level configuration.
self:
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.brain-shell;
  system = pkgs.stdenv.hostPlatform.system;
  home = config.home.homeDirectory;

  # ---- Lua (Hyprland 0.55+) ----
  luaBase = ''
    -- Brain Shell — Hyprland integration
    -- Auto-generated by the Brain Shell Home Manager module. Do not edit.
    hl.layer_rule({ match = { namespace = "^brain-shell.*" }, no_anim = true })
    hl.layer_rule({ match = { namespace = "selection" }, no_anim = true, ignore_alpha = 1 })

    local kb_path = "${home}/.config/Brain_Shell/Brain_ShellKeybinds.lua"
    local f = io.open(kb_path, "r")
    if f then
        f:close()
        dofile(kb_path)
    end
  '';
  luaExecOnce = ''
    hl.on("hyprland.start", function()
        hl.exec_cmd("brain-shell")
    end)
  '';

  # ---- Hyprlang (.conf) ----
  confBase = ''
    # Brain Shell — Hyprland integration
    # Auto-generated by the Brain Shell Home Manager module. Do not edit.
    layerrule = noanim, ^(brain-shell.*)$
    layerrule = noanim, selection
    layerrule = ignorealpha 1, selection
    source = ${home}/.config/Brain_Shell/Brain_ShellKeybinds.conf
  '';
  confExecOnce = ''
    exec-once = brain-shell
  '';

  withAutostart = execOnce: base: if cfg.systemd.enable then base else execOnce + "\n" + base;
in
{
  options.programs.brain-shell = {
    enable = lib.mkEnableOption "Brain Shell UI";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${system}.default;
      defaultText = lib.literalExpression "brain-shell.packages.\${system}.default";
      description = "The Brain Shell package to install.";
    };

    installDeps = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install Brain Shell's runtime dependencies into the user environment.";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression "[ pkgs.envycontrol pkgs.gpu-screen-recorder ]";
      description = "Additional packages to add to the user environment.";
    };

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "kitty";
      description = "Terminal emulator to use.";
    };

    wallpaperDaemon = lib.mkOption {
      type = lib.types.enum [
        "awww"
        "hyprpaper"
        "swaybg"
      ];
      default = "awww";
      description = "Wallpaper daemon to use with Brain Shell.";
    };

    systemd.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Autostart Brain Shell via a systemd user service instead of a Hyprland exec hook.";
    };

    hyprlandIntegration = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Inject Brain Shell layer rules and the keybind source into
          `~/.config/hypr/lua.d/brain-shell.lua` or
          `~/.config/hypr/conf.d/brain-shell.conf`. When `systemd.enable`
          is false, an autostart line is added as well.
        '';
      };

      format = lib.mkOption {
        type = lib.types.enum [
          "lua"
          "conf"
        ];
        default = "lua";
        description = "Injected Hyprland config format. Hyprland 0.55+ uses Lua; conf is a fallback.";
      };
    };

    installDefaultHyprlandConfig = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Install the upstream default Hyprland config template as `~/.config/hypr`.
        WARNING: this manages the whole directory through Home Manager and will
        replace your own Hyprland config. Only enable it on a fresh setup.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      [ cfg.package ]
      ++ cfg.extraPackages
      ++ lib.optionals cfg.installDeps (import ../deps.nix pkgs)
      ++ (with pkgs; [
        nerd-fonts.jetbrains-mono
        nerd-fonts.symbols-only
      ]);

    home.sessionVariables = {
      BRAIN_SHELL_TERMINAL = cfg.terminal;
      BRAIN_SHELL_WALLPAPER_DAEMON = cfg.wallpaperDaemon;
      BRAIN_SHELL_CONFIG_TYPE = cfg.hyprlandIntegration.format;
    };

    systemd.user.services.brain-shell = lib.mkIf cfg.systemd.enable {
      Unit = {
        Description = "Brain Shell session";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
      };
      Service = {
        Type = "exec";
        ExecStart = "${cfg.package}/bin/brain-shell";
        Environment = [
          "QT_QPA_PLATFORMTHEME=qt6ct"
          "XDG_CURRENT_DESKTOP=Hyprland"
          "BRAIN_SHELL_TERMINAL=${cfg.terminal}"
          "BRAIN_SHELL_WALLPAPER_DAEMON=${cfg.wallpaperDaemon}"
        ];
        Restart = "on-failure";
        RestartSec = "5s";
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };

    xdg.configFile."hypr/lua.d/brain-shell.lua" =
      lib.mkIf (cfg.hyprlandIntegration.enable && cfg.hyprlandIntegration.format == "lua")
        { text = withAutostart luaExecOnce luaBase; };

    xdg.configFile."hypr/conf.d/brain-shell.conf" =
      lib.mkIf (cfg.hyprlandIntegration.enable && cfg.hyprlandIntegration.format == "conf")
        { text = withAutostart confExecOnce confBase; };

    xdg.configFile."hypr" = lib.mkIf cfg.installDefaultHyprlandConfig {
      source = "${cfg.package}/share/brain-shell/src/config/hypr_template";
      recursive = true;
    };
  };
}
